[project]
name = "djpwr"
description = "Django for Power Users"
version = "0.0.3"
authors = [
    { name = "Ruude de Klerk", email = "ruud@codeveloped.nl" }
]
dependencies = [
]

[project.optional-dependencies]
dev = [
]
